name: Build exe

on:
  push:
    branches:
      - master  # 你的主要分支

jobs:
  build:
    runs-on: ubuntu-latest  # 使用 Ubuntu 环境，你也可以选择其他环境

    steps:
    - name: Checkout code
      uses: actions/checkout@v2  # 检出代码

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '2.7'  # 替换为你的 Python 版本

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pyinstaller  # 安装 pyinstaller

    - name: Build exe
      run: pyinstaller --onefile lpunpack.py  # 替换 your_script.py 为你的 Python 文件名
